### ISSUE TITLE
Getting AttributeError on Windows 64

### ISSUE THREAD

**Issue by lucode** [GrappigPanda/pygemony#153]
running pygemoney on my windows 10 64bit gets an error:
repo: [https://github.com/codoo/odoo-project_scrum/issues]
```
 langs = [i for i in self.github.get_languages()]
  File "c:\python27\lib\site-packages\pyg\github.py", line 64, in get_languages
    for i in self.curr_repo.iter_languages():
   AttributeError: 'NoneType' object has no attribute 'iter_languages'
```

**Comment by GrappigPanda** [comment]
Hey @lucode, would you mind telling me the repository name (with a link) or
the languages the repository is written in?

**Comment by lucode** [comment]
I dee now the problem the language is determind in the subfolder and not in the root!

**Comment by GrappigPanda** [comment]
Thanks for reporting this issue regardless. I currently have it recursively
walk the directories and check starting from the root directory and
depending on each sub-directory that it reaches, it checks file-by-file for
the file-type.
